### ISSUE TITLE
TinyG v9 support

### ISSUE THREAD

**Issue by adeebshihadeh** [mattstock/android-tinyg#3]
What would I need to do to get this working with a TinyG v9?

**Comment by mattstock** [comment]
I'm not familiar with the v9 hardware, however if it is protocol-compatible with v8 it should work fine.

The bigger challenge with this app is that is relies on host mode for direct connection.  As far as I'm aware, the TinyG project doesn't have their own USB ID, making it a little bit tricky to make sure that the app enumerates the devices correctly and connects.  There is a debug mode that logs all of the IO that goes to and from the app which can help with figuring out anything special that might have thrown the comms off.

If you do end up updating the code, I'd be happy to accept pull requests and update the app in the store.
